package com.seckill.dao;

import com.seckill.dataobject.AccountFlowDO;

public interface AccountFlowDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    int insert(AccountFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    int insertSelective(AccountFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    AccountFlowDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    int updateByPrimaryKeySelective(AccountFlowDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_flow
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    int updateByPrimaryKey(AccountFlowDO record);
}