package com.seckill.dao;

import com.seckill.dataobject.AnnounceDO;

import java.util.List;

public interface AnnounceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    int insert(AnnounceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    int insertSelective(AnnounceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    AnnounceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    int updateByPrimaryKeySelective(AnnounceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    int updateByPrimaryKey(AnnounceDO record);

    List<AnnounceDO> selectAnnounceDOByUserId(Integer userId);
}