package com.seckill.dao;

import com.seckill.dataobject.ManagerPermissionDO;

public interface ManagerPermissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_permission
     *
     * @mbg.generated Sat Mar 19 14:03:24 CST 2022
     */
    int deleteByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_permission
     *
     * @mbg.generated Sat Mar 19 14:03:24 CST 2022
     */
    int insert(ManagerPermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_permission
     *
     * @mbg.generated Sat Mar 19 14:03:24 CST 2022
     */
    int insertSelective(ManagerPermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_permission
     *
     * @mbg.generated Sat Mar 19 14:03:24 CST 2022
     */
    ManagerPermissionDO selectByPrimaryKey(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_permission
     *
     * @mbg.generated Sat Mar 19 14:03:24 CST 2022
     */
    int updateByPrimaryKeySelective(ManagerPermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_permission
     *
     * @mbg.generated Sat Mar 19 14:03:24 CST 2022
     */
    int updateByPrimaryKey(ManagerPermissionDO record);
}