package com.seckill.dao;

import com.seckill.dataobject.ManagerDO;

public interface ManagerDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    int insert(ManagerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    int insertSelective(ManagerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    ManagerDO selectByPrimaryKey(Integer id);

    ManagerDO selectByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    int updateByPrimaryKeySelective(ManagerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_info
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    int updateByPrimaryKey(ManagerDO record);
}