package com.seckill.dao;

import com.seckill.dataobject.OverdueRecordDO;

import java.util.List;

public interface OverdueRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    List<OverdueRecordDO> selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    int insert(OverdueRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    int insertSelective(OverdueRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    OverdueRecordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    int updateByPrimaryKeySelective(OverdueRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overdue_record
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    int updateByPrimaryKey(OverdueRecordDO record);
}