package com.seckill.dao;

import com.seckill.dataobject.ProductDO;
import org.apache.ibatis.annotations.Param;
import org.w3c.dom.stylesheets.LinkStyle;

import java.util.List;

public interface ProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    int insert(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    int insertSelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    ProductDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    int updateByPrimaryKeySelective(ProductDO record);
    List<ProductDO> listProduct();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    int updateByPrimaryKey(ProductDO record);
    int increaseSales(@Param("id")Integer id,@Param("amount")Integer amount);

}