package com.seckill.dao;

import com.seckill.dataobject.ScreenRuleDO;

public interface ScreenRuleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_rule
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_rule
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    int insert(ScreenRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_rule
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    int insertSelective(ScreenRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_rule
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    ScreenRuleDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_rule
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    int updateByPrimaryKeySelective(ScreenRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screen_rule
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    int updateByPrimaryKey(ScreenRuleDO record);
}