package com.seckill.dao;

import com.seckill.dataobject.StockDO;
import org.apache.ibatis.annotations.Param;

public interface StockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Mar 05 15:48:15 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Mar 05 15:48:15 CST 2022
     */
    int insert(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Mar 05 15:48:15 CST 2022
     */
    int insertSelective(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Mar 05 15:48:15 CST 2022
     */
    StockDO selectByPrimaryKey(Integer id);
    StockDO selectByProductId(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Mar 05 15:48:15 CST 2022
     */
    int updateByPrimaryKeySelective(StockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Sat Mar 05 15:48:15 CST 2022
     */
    int updateByPrimaryKey(StockDO record);

    int decreaseStock(@Param("productId") Integer productId, @Param("amount") Integer amount);
    int increaseStock(@Param("productId") Integer productId, @Param("amount") Integer amount);

}