package com.seckill.dao;

import com.seckill.dataobject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpassword
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpassword
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpassword
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    int insertSelective(UserPasswordDO record);


    UserPasswordDO selectByUserId(Integer userID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpassword
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    UserPasswordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpassword
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpassword
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    int updateByPrimaryKey(UserPasswordDO record);
}