package com.seckill.dataobject;

//import io.swagger.annotations.ApiModel;
//import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

//@ApiModel("用户账户模型")
public class AccountDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.id
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */

    //@ApiModelProperty("账户id")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.available_balance
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    //@ApiModelProperty("账户余额")
    private Double availableBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.all_profit
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    //@ApiModelProperty("总收入")
    private Double allProfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.all_expend
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    //@ApiModelProperty("总支出")
    private Double allExpend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.user_id
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    //@ApiModelProperty("用户id")
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.id
     *
     * @return the value of account_info.id
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.id
     *
     * @param id the value for account_info.id
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.available_balance
     *
     * @return the value of account_info.available_balance
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public Double getAvailableBalance() {
        return availableBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.available_balance
     *
     * @param availableBalance the value for account_info.available_balance
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public void setAvailableBalance(Double availableBalance) {
        this.availableBalance = availableBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.all_profit
     *
     * @return the value of account_info.all_profit
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public Double getAllProfit() {
        return allProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.all_profit
     *
     * @param allProfit the value for account_info.all_profit
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public void setAllProfit(Double allProfit) {
        this.allProfit = allProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.all_expend
     *
     * @return the value of account_info.all_expend
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public Double getAllExpend() {
        return allExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.all_expend
     *
     * @param allExpend the value for account_info.all_expend
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public void setAllExpend(Double allExpend) {
        this.allExpend = allExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.user_id
     *
     * @return the value of account_info.user_id
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.user_id
     *
     * @param userId the value for account_info.user_id
     *
     * @mbg.generated Fri Mar 04 19:25:56 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}