package com.seckill.dataobject;

import java.util.Date;

public class AccountFlowDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.id
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.account_id
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.time
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.change_money
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    private Double changeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_flow.msg
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.id
     *
     * @return the value of account_flow.id
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.id
     *
     * @param id the value for account_flow.id
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.account_id
     *
     * @return the value of account_flow.account_id
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.account_id
     *
     * @param accountId the value for account_flow.account_id
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.time
     *
     * @return the value of account_flow.time
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.time
     *
     * @param time the value for account_flow.time
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.change_money
     *
     * @return the value of account_flow.change_money
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public Double getChangeMoney() {
        return changeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.change_money
     *
     * @param changeMoney the value for account_flow.change_money
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public void setChangeMoney(Double changeMoney) {
        this.changeMoney = changeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_flow.msg
     *
     * @return the value of account_flow.msg
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_flow.msg
     *
     * @param msg the value for account_flow.msg
     *
     * @mbg.generated Mon Mar 14 16:52:12 CST 2022
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}