package com.seckill.dataobject;

import java.util.Date;

public class AnnounceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.id
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.user_id
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.content
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.post_time
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    private Date postTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.flag
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    private Byte flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.id
     *
     * @return the value of announce.id
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.id
     *
     * @param id the value for announce.id
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.user_id
     *
     * @return the value of announce.user_id
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.user_id
     *
     * @param userId the value for announce.user_id
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.content
     *
     * @return the value of announce.content
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.content
     *
     * @param content the value for announce.content
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.post_time
     *
     * @return the value of announce.post_time
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public Date getPostTime() {
        return postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.post_time
     *
     * @param postTime the value for announce.post_time
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.flag
     *
     * @return the value of announce.flag
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.flag
     *
     * @param flag the value for announce.flag
     *
     * @mbg.generated Wed Apr 06 14:09:29 CST 2022
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}