package com.seckill.dataobject;

public class ManagerDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.id
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.password
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.nick_name
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.phone
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_info.task
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    private String task;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.id
     *
     * @return the value of manager_info.id
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.id
     *
     * @param id the value for manager_info.id
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.password
     *
     * @return the value of manager_info.password
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.password
     *
     * @param password the value for manager_info.password
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.nick_name
     *
     * @return the value of manager_info.nick_name
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.nick_name
     *
     * @param nickName the value for manager_info.nick_name
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.phone
     *
     * @return the value of manager_info.phone
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.phone
     *
     * @param phone the value for manager_info.phone
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_info.task
     *
     * @return the value of manager_info.task
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public String getTask() {
        return task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_info.task
     *
     * @param task the value for manager_info.task
     *
     * @mbg.generated Sat Mar 19 13:56:46 CST 2022
     */
    public void setTask(String task) {
        this.task = task == null ? null : task.trim();
    }
}