package com.seckill.dataobject;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

@ApiModel("订单模型")
public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("订单编号")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("用户编号")
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.product_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("银行商品编号")
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_money
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("支付金额")
    private Double payMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_time
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("支付时间")
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.num
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("商品数量")
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("下单时间")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("订单状态")
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.seckill_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    @ApiModelProperty("秒杀活动id")
    private Integer seckillId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.product_id
     *
     * @return the value of order_info.product_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.product_id
     *
     * @param productId the value for order_info.product_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_money
     *
     * @return the value of order_info.pay_money
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public Double getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_money
     *
     * @param payMoney the value for order_info.pay_money
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setPayMoney(Double payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_time
     *
     * @return the value of order_info.pay_time
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_time
     *
     * @param payTime the value for order_info.pay_time
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.num
     *
     * @return the value of order_info.num
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.num
     *
     * @param amount the value for order_info.num
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order_info.create_time
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order_info.create_time
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.seckill_id
     *
     * @return the value of order_info.seckill_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public Integer getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.seckill_id
     *
     * @param seckillId the value for order_info.seckill_id
     *
     * @mbg.generated Sat Mar 05 21:05:53 CST 2022
     */
    public void setSeckillId(Integer seckillId) {
        this.seckillId = seckillId;
    }
}