package com.seckill.dataobject;

import java.util.Date;

public class OverdueRecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue_record.id
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue_record.user_id
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue_record.behind_time_day
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    private Integer behindTimeDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue_record.behind_time_money
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    private Double behindTimeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overdue_record.time
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue_record.id
     *
     * @return the value of overdue_record.id
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue_record.id
     *
     * @param id the value for overdue_record.id
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue_record.user_id
     *
     * @return the value of overdue_record.user_id
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue_record.user_id
     *
     * @param userId the value for overdue_record.user_id
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue_record.behind_time_day
     *
     * @return the value of overdue_record.behind_time_day
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public Integer getBehindTimeDay() {
        return behindTimeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue_record.behind_time_day
     *
     * @param behindTimeDay the value for overdue_record.behind_time_day
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public void setBehindTimeDay(Integer behindTimeDay) {
        this.behindTimeDay = behindTimeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue_record.behind_time_money
     *
     * @return the value of overdue_record.behind_time_money
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public Double getBehindTimeMoney() {
        return behindTimeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue_record.behind_time_money
     *
     * @param behindTimeMoney the value for overdue_record.behind_time_money
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public void setBehindTimeMoney(Double behindTimeMoney) {
        this.behindTimeMoney = behindTimeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overdue_record.time
     *
     * @return the value of overdue_record.time
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overdue_record.time
     *
     * @param time the value for overdue_record.time
     *
     * @mbg.generated Sun Mar 13 16:49:18 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }
}