package com.seckill.dataobject;

import java.util.Date;

public class ProductDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.id
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.deadline
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Integer deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.rate
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Double rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.start_amount
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Double startAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.incre_amount
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Double increAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.person_limit
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Double personLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.day_limit
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Double dayLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.risk
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private String risk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.value_date
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Date valueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.method
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.end_date
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.sales
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.description
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.flag
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    private Byte flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.id
     *
     * @return the value of product_info.id
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.id
     *
     * @param id the value for product_info.id
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.deadline
     *
     * @return the value of product_info.deadline
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Integer getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.deadline
     *
     * @param deadline the value for product_info.deadline
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setDeadline(Integer deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.rate
     *
     * @return the value of product_info.rate
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.rate
     *
     * @param rate the value for product_info.rate
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.start_amount
     *
     * @return the value of product_info.start_amount
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Double getStartAmount() {
        return startAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.start_amount
     *
     * @param startAmount the value for product_info.start_amount
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setStartAmount(Double startAmount) {
        this.startAmount = startAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.incre_amount
     *
     * @return the value of product_info.incre_amount
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Double getIncreAmount() {
        return increAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.incre_amount
     *
     * @param increAmount the value for product_info.incre_amount
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setIncreAmount(Double increAmount) {
        this.increAmount = increAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.person_limit
     *
     * @return the value of product_info.person_limit
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Double getPersonLimit() {
        return personLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.person_limit
     *
     * @param personLimit the value for product_info.person_limit
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setPersonLimit(Double personLimit) {
        this.personLimit = personLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.day_limit
     *
     * @return the value of product_info.day_limit
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Double getDayLimit() {
        return dayLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.day_limit
     *
     * @param dayLimit the value for product_info.day_limit
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setDayLimit(Double dayLimit) {
        this.dayLimit = dayLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.risk
     *
     * @return the value of product_info.risk
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public String getRisk() {
        return risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.risk
     *
     * @param risk the value for product_info.risk
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setRisk(String risk) {
        this.risk = risk == null ? null : risk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.value_date
     *
     * @return the value of product_info.value_date
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Date getValueDate() {
        return valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.value_date
     *
     * @param valueDate the value for product_info.value_date
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setValueDate(Date valueDate) {
        this.valueDate = valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.method
     *
     * @return the value of product_info.method
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.method
     *
     * @param method the value for product_info.method
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.end_date
     *
     * @return the value of product_info.end_date
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.end_date
     *
     * @param endDate the value for product_info.end_date
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.sales
     *
     * @return the value of product_info.sales
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.sales
     *
     * @param sales the value for product_info.sales
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.description
     *
     * @return the value of product_info.description
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.description
     *
     * @param description the value for product_info.description
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.flag
     *
     * @return the value of product_info.flag
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.flag
     *
     * @param flag the value for product_info.flag
     *
     * @mbg.generated Sat Mar 05 15:47:35 CST 2022
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}