package com.seckill.dataobject;

import java.util.Date;

public class ScreenRuleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.id
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.behind_time_day
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Integer behindTimeDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.behind_time_money
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Double behindTimeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.behind_time_num
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Integer behindTimeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.flag
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Byte flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.min_age
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Integer minAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.work_state
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Integer workState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.dishonest
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Integer dishonest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screen_rule.value_time
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    private Date valueTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.id
     *
     * @return the value of screen_rule.id
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.id
     *
     * @param id the value for screen_rule.id
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.behind_time_day
     *
     * @return the value of screen_rule.behind_time_day
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Integer getBehindTimeDay() {
        return behindTimeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.behind_time_day
     *
     * @param behindTimeDay the value for screen_rule.behind_time_day
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setBehindTimeDay(Integer behindTimeDay) {
        this.behindTimeDay = behindTimeDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.behind_time_money
     *
     * @return the value of screen_rule.behind_time_money
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Double getBehindTimeMoney() {
        return behindTimeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.behind_time_money
     *
     * @param behindTimeMoney the value for screen_rule.behind_time_money
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setBehindTimeMoney(Double behindTimeMoney) {
        this.behindTimeMoney = behindTimeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.behind_time_num
     *
     * @return the value of screen_rule.behind_time_num
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Integer getBehindTimeNum() {
        return behindTimeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.behind_time_num
     *
     * @param behindTimeNum the value for screen_rule.behind_time_num
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setBehindTimeNum(Integer behindTimeNum) {
        this.behindTimeNum = behindTimeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.flag
     *
     * @return the value of screen_rule.flag
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.flag
     *
     * @param flag the value for screen_rule.flag
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.min_age
     *
     * @return the value of screen_rule.min_age
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Integer getMinAge() {
        return minAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.min_age
     *
     * @param minAge the value for screen_rule.min_age
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setMinAge(Integer minAge) {
        this.minAge = minAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.work_state
     *
     * @return the value of screen_rule.work_state
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Integer getWorkState() {
        return workState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.work_state
     *
     * @param workState the value for screen_rule.work_state
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setWorkState(Integer workState) {
        this.workState = workState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.dishonest
     *
     * @return the value of screen_rule.dishonest
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Integer getDishonest() {
        return dishonest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.dishonest
     *
     * @param dishonest the value for screen_rule.dishonest
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setDishonest(Integer dishonest) {
        this.dishonest = dishonest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screen_rule.value_time
     *
     * @return the value of screen_rule.value_time
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public Date getValueTime() {
        return valueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screen_rule.value_time
     *
     * @param valueTime the value for screen_rule.value_time
     *
     * @mbg.generated Sun Mar 13 19:18:08 CST 2022
     */
    public void setValueTime(Date valueTime) {
        this.valueTime = valueTime;
    }
}