package com.seckill.dataobject;

import java.util.Date;

public class SeckillLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_log.id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_log.seckill_id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    private Integer seckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_log.user_id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_log.user_name
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_log.status
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_log.time
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_log.msg
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_log.id
     *
     * @return the value of seckill_log.id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_log.id
     *
     * @param id the value for seckill_log.id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_log.seckill_id
     *
     * @return the value of seckill_log.seckill_id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public Integer getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_log.seckill_id
     *
     * @param seckillId the value for seckill_log.seckill_id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public void setSeckillId(Integer seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_log.user_id
     *
     * @return the value of seckill_log.user_id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_log.user_id
     *
     * @param userId the value for seckill_log.user_id
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_log.user_name
     *
     * @return the value of seckill_log.user_name
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_log.user_name
     *
     * @param userName the value for seckill_log.user_name
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_log.status
     *
     * @return the value of seckill_log.status
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_log.status
     *
     * @param status the value for seckill_log.status
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_log.time
     *
     * @return the value of seckill_log.time
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_log.time
     *
     * @param time the value for seckill_log.time
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_log.msg
     *
     * @return the value of seckill_log.msg
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_log.msg
     *
     * @param msg the value for seckill_log.msg
     *
     * @mbg.generated Sun Mar 13 20:08:26 CST 2022
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}