package com.seckill.dataobject;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpassword.id
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpassword.encrpt_password
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    private String encrptPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpassword.user_id
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpassword.id
     *
     * @return the value of userpassword.id
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpassword.id
     *
     * @param id the value for userpassword.id
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpassword.encrpt_password
     *
     * @return the value of userpassword.encrpt_password
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    public String getEncrptPassword() {
        return encrptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpassword.encrpt_password
     *
     * @param encrptPassword the value for userpassword.encrpt_password
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    public void setEncrptPassword(String encrptPassword) {
        this.encrptPassword = encrptPassword == null ? null : encrptPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpassword.user_id
     *
     * @return the value of userpassword.user_id
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpassword.user_id
     *
     * @param userId the value for userpassword.user_id
     *
     * @mbg.generated Thu Mar 03 16:51:13 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}